### ISSUE TITLE
Base R pipe to first unnamed argument

### ISSUE THREAD

**Issue by EconProf** [bwiernik/pipebind#4]
A minor suggested change to the README. For the base R pipe, the piped object appears as the first **unnamed** argument, which may not be the first argument. In some cases, this is the easiest solution. For others, there is {pipebind}!

mtcars |> lm(mpg ~ wt + cyl) returns an error, but

mtcars |> lm(formula = mpg ~ wt + cyl) is OK.

**Comment by bwiernik** [comment]
Thanks. Feel free to make a pull request adding "unnamed". 

Personally, I am not a fan of relying on the first unnamed behavior. For example, it works fine for lm(), but for glm(), you need to specify both `formula` and `family` by name to get to `data`.  For `metafor::rma()`, you need to name over a dozen arguments before you finally get to `data`. The placement of the `data` argument is so inconsistent across functions that I recommend only using the first argument, `_`, or `bind()`

**Comment by EconProf** [comment]
You are right. It would be best not to show students an "easy" way that is not so easy when there are multiple arguments that would need to be named. We will stick to `_` and `bind()` and I do not see a need to complicate it with another option. 

This is only the second time I filed an issue. Do I need to close it?

**Comment by bwiernik** [comment]
Thanks for the helpful discussion!
